### ISSUE TITLE
Trouble with parsing some formats

### ISSUE THREAD

**Issue by SimplGy** [KeepSafe/genstrings_swift#1]
Hi there!

Thought I'd give this a try, because genstrings [doesn't work](https://openradar.appspot.com/22133811) for the non-trivial case of NSLocalizedString. Looked like this might, but I think it has trouble with some newline or other structures.

I know regex is hard to write in a general way...

Example file:

``` swift
struct Localized {
  struct Confirm {
    static let message        = NSLocalizedString("Confirm-message",           value: "Are you sure?",
      comment: "asking if they are sure they want to do some questionable action")
    static let cancelTitle    = NSLocalizedString("Confirm-cancelTitle",       value: "Cancel",
      comment: "default/cancel title")
  }

  struct Account {
    static let signOut        = NSLocalizedString("Account-signOut",           value: "Sign Out",
      comment: "Sign Out button title")
    static let connected      = NSLocalizedString("Account-connected",         value: "(Connected)",
      comment: "External authentication is connected")
    static let notConnected   = NSLocalizedString("Account-notConnected",      value: "(Not Connected)",
      comment: "External authentication is not connected")
  }
}
```

Could be the newlines, something else, I'm not sure. I'm taking a look but really just want the fastest solution, hacky or no, so I might not PR a generalizable, complete solution.

**Comment by philippb** [comment]
Hi there,
thanks for pointing this out. I think this might be the nested structs. We have all our strings as global constants with a prefix.

```
let LOC_OK = NSLocalizedString("KS_OK", value: "OK", comment: "")
```

The newline should be fie as we have plenty of lines where we split the arguments into a new line.
Thanks for looking at it. Even if your solution is very dirty, would be great if you could open a PR. Happy to make it nice over here.

**Comment by SimplGy** [comment]
I ended up exporting localizations to xliff and importing them back in after translation. This works ok (as in: Xcode finds all the source translation strings, and tools to edit xliff exist) and I think us where apple is heading.

Sorry to let you down :cry:
